--------------------------------------------------------
--  Fichier cr�� - samedi-d�cembre-03-2022   
--------------------------------------------------------
DROP TABLE "SYSTEM"."AFFAIRE_JURIDIQUE";
DROP TABLE "SYSTEM"."AVOCAT";
DROP TABLE "SYSTEM"."CONGE";
DROP TABLE "SYSTEM"."JUGE";
DROP TABLE "SYSTEM"."JUGER";
DROP TABLE "SYSTEM"."ORGANISER";
DROP TABLE "SYSTEM"."PERSONNEL";
DROP TABLE "SYSTEM"."PLAIDER";
DROP TABLE "SYSTEM"."SALLE_AUDIENCE";
--------------------------------------------------------
--  DDL for Table AFFAIRE_JURIDIQUE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."AFFAIRE_JURIDIQUE" 
   (	"NUMCAS" VARCHAR2(8 BYTE), 
	"CIN" VARCHAR2(8 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"TYPECAS" VARCHAR2(20 BYTE), 
	"DATECAS" VARCHAR2(10 BYTE), 
	"DATENESS" VARCHAR2(10 BYTE), 
	"ETAT_CAS" VARCHAR2(20 BYTE), 
	"SEXE" VARCHAR2(20 BYTE), 
	"METIER" VARCHAR2(20 BYTE), 
	"NBENFANT" VARCHAR2(3 BYTE), 
	"ID_SALLE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table AVOCAT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."AVOCAT" 
   (	"ID_AVOCAT" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"DATE_NAISSANCE" VARCHAR2(20 BYTE), 
	"NOMBRE_PROCES_GAGNES" NUMBER, 
	"NUMERO_TELEPHONE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONGE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CONGE" 
   (	"ID_AVOCAT" NUMBER, 
	"DATE_DEBUT" VARCHAR2(20 BYTE), 
	"DATE_FIN" VARCHAR2(20 BYTE), 
	"MOTIF" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table JUGE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."JUGE" 
   (	"CIN_J" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"NUM_BUREAU" VARCHAR2(20 BYTE), 
	"NB_PROCESS_GAGNER" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table JUGER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."JUGER" 
   (	"CIN_J" VARCHAR2(20 BYTE), 
	"NUMCAS" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORGANISER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ORGANISER" 
   (	"CIN_P" NUMBER, 
	"ID_SALLE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSONNEL
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PERSONNEL" 
   (	"CIN_P" NUMBER, 
	"PRENOM" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"DATE_DE_NAISSANCE" VARCHAR2(20 BYTE), 
	"ROLE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PLAIDER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PLAIDER" 
   (	"ID_AVOCAT" NUMBER, 
	"NUMCAS" VARCHAR2(8 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SALLE_AUDIENCE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."SALLE_AUDIENCE" 
   (	"ID_SALLE" NUMBER, 
	"NOMBRES_CAMER_ACTIVEES" NUMBER, 
	"NOMBRE_PLACES_TOTAL" NUMBER, 
	"DISPONIBILTE" VARCHAR2(4 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.AFFAIRE_JURIDIQUE
SET DEFINE OFF;
Insert into SYSTEM.AFFAIRE_JURIDIQUE (NUMCAS,CIN,NOM,PRENOM,TYPECAS,DATECAS,DATENESS,ETAT_CAS,SEXE,METIER,NBENFANT,ID_SALLE) values ('123','14785236','hh','gg','gg',null,null,null,null,null,null,null);
Insert into SYSTEM.AFFAIRE_JURIDIQUE (NUMCAS,CIN,NOM,PRENOM,TYPECAS,DATECAS,DATENESS,ETAT_CAS,SEXE,METIER,NBENFANT,ID_SALLE) values ('0704','88480541','ijjah','rekas','lenmirc','2102/90/82','1002/50/82','ruoc ne','emmoh','evele','0',null);
Insert into SYSTEM.AFFAIRE_JURIDIQUE (NUMCAS,CIN,NOM,PRENOM,TYPECAS,DATECAS,DATENESS,ETAT_CAS,SEXE,METIER,NBENFANT,ID_SALLE) values ('321','63852741','nimsay','ddd','tt','2202/21/20','2002/50/51','ko','emmaf','evele','0',null);
REM INSERTING into SYSTEM.AVOCAT
SET DEFINE OFF;
Insert into SYSTEM.AVOCAT (ID_AVOCAT,NOM,PRENOM,DATE_NAISSANCE,NOMBRE_PROCES_GAGNES,NUMERO_TELEPHONE) values ('123355','gadhoumi','eya','24/10/2000','1','23067230');
Insert into SYSTEM.AVOCAT (ID_AVOCAT,NOM,PRENOM,DATE_NAISSANCE,NOMBRE_PROCES_GAGNES,NUMERO_TELEPHONE) values ('654545','sd','sqd','18/05/2001','1','565656');
REM INSERTING into SYSTEM.CONGE
SET DEFINE OFF;
Insert into SYSTEM.CONGE (ID_AVOCAT,DATE_DEBUT,DATE_FIN,MOTIF) values ('123355','02/12/2022','11/12/2022','FS');
REM INSERTING into SYSTEM.JUGE
SET DEFINE OFF;
Insert into SYSTEM.JUGE (CIN_J,NOM,PRENOM,NUM_BUREAU,NB_PROCESS_GAGNER) values ('14508488','SYSTEM','hajji','14','1');
REM INSERTING into SYSTEM.JUGER
SET DEFINE OFF;
REM INSERTING into SYSTEM.ORGANISER
SET DEFINE OFF;
REM INSERTING into SYSTEM.PERSONNEL
SET DEFINE OFF;
Insert into SYSTEM.PERSONNEL (CIN_P,PRENOM,NOM,DATE_DE_NAISSANCE,ROLE) values ('14508488','SYSTEM','hajji','28/05/2001','AJ');
Insert into SYSTEM.PERSONNEL (CIN_P,PRENOM,NOM,DATE_DE_NAISSANCE,ROLE) values ('14775477','yassmin','grara','15/05/2002','GG');
Insert into SYSTEM.PERSONNEL (CIN_P,PRENOM,NOM,DATE_DE_NAISSANCE,ROLE) values ('14515511','eya','ghadhoumi','24/10/2002','GV');
REM INSERTING into SYSTEM.PLAIDER
SET DEFINE OFF;
REM INSERTING into SYSTEM.SALLE_AUDIENCE
SET DEFINE OFF;
Insert into SYSTEM.SALLE_AUDIENCE (ID_SALLE,NOMBRES_CAMER_ACTIVEES,NOMBRE_PLACES_TOTAL,DISPONIBILTE) values ('180','3','5','o');
Insert into SYSTEM.SALLE_AUDIENCE (ID_SALLE,NOMBRES_CAMER_ACTIVEES,NOMBRE_PLACES_TOTAL,DISPONIBILTE) values ('123','2','7','oui');
--------------------------------------------------------
--  DDL for Index AFFAIRE_JURIDIQUE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."AFFAIRE_JURIDIQUE_PK" ON "SYSTEM"."AFFAIRE_JURIDIQUE" ("NUMCAS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_AVOCAT
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_AVOCAT" ON "SYSTEM"."AVOCAT" ("ID_AVOCAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_JUGE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_JUGE" ON "SYSTEM"."JUGE" ("CIN_J") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_PER
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_PER" ON "SYSTEM"."PERSONNEL" ("CIN_P") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_SALLE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_SALLE" ON "SYSTEM"."SALLE_AUDIENCE" ("ID_SALLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table AFFAIRE_JURIDIQUE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."AFFAIRE_JURIDIQUE" ADD CONSTRAINT "AFFAIRE_JURIDIQUE_PK" PRIMARY KEY ("NUMCAS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."AFFAIRE_JURIDIQUE" MODIFY ("NUMCAS" NOT NULL DISABLE VALIDATE);
--------------------------------------------------------
--  Constraints for Table AVOCAT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."AVOCAT" ADD CONSTRAINT "PK_AVOCAT" PRIMARY KEY ("ID_AVOCAT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."AVOCAT" MODIFY ("ID_AVOCAT" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."AVOCAT" MODIFY ("NOM" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."AVOCAT" MODIFY ("PRENOM" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."AVOCAT" MODIFY ("DATE_NAISSANCE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."AVOCAT" MODIFY ("NOMBRE_PROCES_GAGNES" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."AVOCAT" MODIFY ("NUMERO_TELEPHONE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONGE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CONGE" MODIFY ("ID_AVOCAT" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CONGE" MODIFY ("DATE_DEBUT" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CONGE" MODIFY ("DATE_FIN" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CONGE" MODIFY ("MOTIF" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JUGE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."JUGE" ADD CONSTRAINT "PK_JUGE" PRIMARY KEY ("CIN_J")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."JUGE" MODIFY ("CIN_J" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."JUGE" MODIFY ("NOM" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."JUGE" MODIFY ("PRENOM" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."JUGE" MODIFY ("NUM_BUREAU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JUGER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."JUGER" MODIFY ("CIN_J" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."JUGER" MODIFY ("NUMCAS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORGANISER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ORGANISER" MODIFY ("CIN_P" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."ORGANISER" MODIFY ("ID_SALLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONNEL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PERSONNEL" ADD CONSTRAINT "PK_PER" PRIMARY KEY ("CIN_P")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."PERSONNEL" MODIFY ("CIN_P" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."PERSONNEL" MODIFY ("PRENOM" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."PERSONNEL" MODIFY ("NOM" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."PERSONNEL" MODIFY ("DATE_DE_NAISSANCE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."PERSONNEL" MODIFY ("ROLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLAIDER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PLAIDER" MODIFY ("ID_AVOCAT" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."PLAIDER" MODIFY ("NUMCAS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SALLE_AUDIENCE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."SALLE_AUDIENCE" ADD CONSTRAINT "PK_SALLE" PRIMARY KEY ("ID_SALLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."SALLE_AUDIENCE" MODIFY ("ID_SALLE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."SALLE_AUDIENCE" MODIFY ("NOMBRE_PLACES_TOTAL" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."SALLE_AUDIENCE" MODIFY ("DISPONIBILTE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."SALLE_AUDIENCE" MODIFY ("NOMBRES_CAMER_ACTIVEES" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table AFFAIRE_JURIDIQUE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."AFFAIRE_JURIDIQUE" ADD CONSTRAINT "FG_SALLE" FOREIGN KEY ("ID_SALLE")
	  REFERENCES "SYSTEM"."SALLE_AUDIENCE" ("ID_SALLE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONGE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CONGE" ADD CONSTRAINT "FK_CNSTR" FOREIGN KEY ("ID_AVOCAT")
	  REFERENCES "SYSTEM"."AVOCAT" ("ID_AVOCAT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JUGER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."JUGER" ADD CONSTRAINT "FK_AFFJUG" FOREIGN KEY ("NUMCAS")
	  REFERENCES "SYSTEM"."AFFAIRE_JURIDIQUE" ("NUMCAS") ENABLE;
 
  ALTER TABLE "SYSTEM"."JUGER" ADD CONSTRAINT "FK_J" FOREIGN KEY ("CIN_J")
	  REFERENCES "SYSTEM"."JUGE" ("CIN_J") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORGANISER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ORGANISER" ADD CONSTRAINT "FK_PEERSO" FOREIGN KEY ("CIN_P")
	  REFERENCES "SYSTEM"."PERSONNEL" ("CIN_P") ENABLE;
 
  ALTER TABLE "SYSTEM"."ORGANISER" ADD CONSTRAINT "FK_SALLE" FOREIGN KEY ("ID_SALLE")
	  REFERENCES "SYSTEM"."SALLE_AUDIENCE" ("ID_SALLE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLAIDER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PLAIDER" ADD CONSTRAINT "FK_AVAF" FOREIGN KEY ("NUMCAS")
	  REFERENCES "SYSTEM"."AFFAIRE_JURIDIQUE" ("NUMCAS") ENABLE;
 
  ALTER TABLE "SYSTEM"."PLAIDER" ADD CONSTRAINT "PGAV" FOREIGN KEY ("ID_AVOCAT")
	  REFERENCES "SYSTEM"."AVOCAT" ("ID_AVOCAT") ENABLE;
